AWSTemplateFormatVersion: 2010-09-09

Description: N/A

Parameters:
  BucketName:
    Description: Name your Bucket
    Type: String
    

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Environment
          Value: non-production

Outputs:
  S3Bucket:
    Value: !Ref S3Bucket
    Description: Bucket Name