AWSTemplateFormatVersion: 2010-09-09

Description: N/A

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      # Name your Bucket
      BucketName: ericyicameraphoto
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Environment
          Value: non-production

Outputs:
  S3Bucket:
    Value: !Ref S3Bucket
    Description: Bucket Name